attempt to fix localnets routing problem

diff --git a/patches/701-luci-freifunk-policyrouting-berlin.patch b/patches/701-luci-freifunk-policyrouting-berlin.patch
--- a/patches/701-luci-freifunk-policyrouting-berlin.patch
+++ b/patches/701-luci-freifunk-policyrouting-berlin.patch
@@ -25,7 +25,7 @@ Index: openwrt/feeds/luci/contrib/package/freifunk-policyrouting/files/etc/hotpl
  
  config_load freifunk-policyrouting
  config_get enable pr enable
-@@ -13,15 +13,29 @@ config_get strict pr strict
+@@ -13,33 +13,26 @@ config_get strict pr strict
  config_get zones pr zones
  
  if [ "$ACTION" = "ifup" ] && [ "$enable" = "1" ]; then
@@ -44,35 +44,66 @@ Index: openwrt/feeds/luci/contrib/package/freifunk-policyrouting/files/etc/hotpl
 -	if [ "$net" != "" -a -n "$dev" ]; then
 +	if [ "$net" != "" -a -n "${DEVICE}" ]; then
  		eval $(/bin/ipcalc.sh $net)
- 		if [ "$PREFIX" != "0" -a "$NETWORK" != "127.0.0.0" ]; then
+-		if [ "$PREFIX" != "0" -a "$NETWORK" != "127.0.0.0" ]; then
 -			if [ ! "$(ip r s t localnets |grep "$NETWORK/$PREFIX dev")" ]; then
 -				cmd="ip r a $NETWORK/$PREFIX dev $dev table localnets"
-+			if [ ! "$(ip route show table localnets |grep "$NETWORK/$PREFIX dev")" ]; then
-+				cmd="ip route add $NETWORK/$PREFIX dev ${DEVICE} table localnets"
-+				$cmd
-+				if [ "$?" = 0 ]; then
-+					logger -s -t policyrouting "Add route: $cmd"
-+				else
-+					logger -s -t policyrouting "Error! Could not add route: $cmd"
-+				fi
-+			fi
-+			if [ ! "$(ip route show table olsr |grep "$NETWORK/$PREFIX dev")" ]; then
-+				cmd="ip route add $NETWORK/$PREFIX dev ${DEVICE} table olsr"
- 				$cmd
- 				if [ "$?" = 0 ]; then
- 					logger -s -t policyrouting "Add route: $cmd"
-@@ -33,7 +47,7 @@ if [ "$ACTION" = "ifup" ] && [ "$enable"
- 		fi
+-				$cmd
+-				if [ "$?" = 0 ]; then
+-					logger -s -t policyrouting "Add route: $cmd"
+-				else
+-					logger -s -t policyrouting "Error! Could not add route: $cmd"
+-				fi
+-			fi
+-
+-		fi
  
- 		if [ -n "$net6" ]; then
+-		if [ -n "$net6" ]; then
 -			cmd="ip -6 r a $net6 dev $dev table localnets"
-+			cmd="ip -6 route add $net6 dev ${DEVICE} table localnets"
- 			$cmd 2>&1 > /dev/null
- 			if [ "$?" = 0 ]; then
- 				logger -s -t policyrouting "Add route: $cmd (IPv6)"
-@@ -52,51 +66,29 @@ if [ "$ACTION" = "ifup" ] && [ "$enable"
+-			$cmd 2>&1 > /dev/null
+-			if [ "$?" = 0 ]; then
+-				logger -s -t policyrouting "Add route: $cmd (IPv6)"
+-			fi
++		#if [ -n "$net6" ]; then
++		#	cmd="ip -6 route add $net6 dev ${DEVICE} table localnets"
++		#	$cmd 2>&1 > /dev/null
++		#	if [ "$?" = 0 ]; then
++		#		logger -s -t policyrouting "Add route: $cmd (IPv6)"
++		#	fi
+ 
+-		fi
++		#fi
+ 
+ 		networks=""
+ 		for z in $zones; do
+@@ -50,53 +43,55 @@ if [ "$ACTION" = "ifup" ] && [ "$enable"
+ 			networks="$networks $network_zone"
+ 		done
  		for n in $networks; do
++      # Check if interface is part of one of the freifunk zones. We only want to
++      # add routes from interfaces that are part of the freifunk network.
  			if [ "$INTERFACE" = "$n" ]; then
++        # do not add default route and loopback network to localnets table
++        if [ "$PREFIX" != "0" -a "$NETWORK" != "127.0.0.0" ]; then
++          if [ ! "$(ip route show table localnets |grep "$NETWORK/$PREFIX dev")" ]; then
++            cmd="ip route add $NETWORK/$PREFIX dev ${DEVICE} table localnets"
++            $cmd
++            if [ "$?" = 0 ]; then
++              logger -s -t policyrouting "Add route: $cmd"
++            else
++              logger -s -t policyrouting "Error! Could not add route: $cmd"
++            fi
++          fi
++          if [ ! "$(ip route show table olsr |grep "$NETWORK/$PREFIX dev")" ]; then
++            cmd="ip route add $NETWORK/$PREFIX dev ${DEVICE} table olsr"
++            $cmd
++            if [ "$?" = 0 ]; then
++              logger -s -t policyrouting "Add route: $cmd"
++            else
++              logger -s -t policyrouting "Error! Could not add route: $cmd"
++            fi
++          fi
++        fi
++
  				for p in $proto; do
 -					if [ ! "$(ip -$p ru s | grep "from all iif $dev lookup olsr-default")" ]; then
 -						ip -$p rule add dev "$dev" lookup olsr-default prio 20000
@@ -154,7 +185,7 @@ Index: openwrt/feeds/luci/contrib/package/freifunk-policyrouting/files/etc/init.
  [ -f /etc/config/olsrd ] && cfgs="olsrd"
  [ -f /etc/config/olsrd6 ] && cfgs="$cfgs olsrd6"
  
-@@ -92,6 +92,8 @@ add_lookup_rule() {
+@@ -103,6 +103,8 @@ add_lookup_rule() {
  	name=${1/-/_}
  	lookup=$2
  	prio=$3
@@ -163,7 +194,7 @@ Index: openwrt/feeds/luci/contrib/package/freifunk-policyrouting/files/etc/init.
  
  	if [ -z "$name" -o -z "$lookup" -o -z "$prio" ]; then
  		logger -s -t policyrouting "Missing parameters for add_rule!"
-@@ -102,21 +104,57 @@ add_lookup_rule() {
+@@ -113,21 +115,57 @@ add_lookup_rule() {
  			else
  				rule="rule"
  			fi
@@ -179,19 +210,19 @@ Index: openwrt/feeds/luci/contrib/package/freifunk-policyrouting/files/etc/init.
 +		done
 +	fi
 +}
-+
-+add_action_rule() {
-+	name=${1/-/_}
-+	action=$2
-+	prio=$3
-+	in=$4
-+	name=$name"_"${in:-allif}"_"
  
 -			uci batch <<- EOF
 -				set network.${name}ipv${p}="$rule"
 -				set network.${name}ipv${p}.lookup="$lookup"
 -				set network.${name}ipv${p}.priority="$prio"
 -			EOF
++add_action_rule() {
++	name=${1/-/_}
++	action=$2
++	prio=$3
++	in=$4
++	name=$name"_"${in:-allif}"_"
++
 +	if [ -z "$name" -o -z "$action" -o -z "$prio" ]; then
 +		logger -s -t policyrouting "Missing parameters for add_action!"
 +	else
@@ -227,7 +258,7 @@ Index: openwrt/feeds/luci/contrib/package/freifunk-policyrouting/files/etc/init.
  }
  
  start() {
-@@ -124,7 +162,7 @@ start() {
+@@ -135,7 +173,7 @@ start() {
  		logger -s -t policyrouting "Starting policy routing."
  		rt_tables
  		olsrd_intalltables
@@ -236,7 +267,7 @@ Index: openwrt/feeds/luci/contrib/package/freifunk-policyrouting/files/etc/init.
  
  		add_lookup_rule olsr olsr 1000
  		add_lookup_rule localnets localnets 2000
-@@ -132,6 +170,26 @@ start() {
+@@ -143,6 +181,26 @@ start() {
  		if [ "$fallback" = 1 ]; then
  			add_lookup_rule olsr-default olsr-default 100000
  		fi
@@ -263,7 +294,7 @@ Index: openwrt/feeds/luci/contrib/package/freifunk-policyrouting/files/etc/init.
  	fi
  	uci commit network
  	if [ ! "$1" = "noservicerestart" ]; then
-@@ -142,20 +200,33 @@ start() {
+@@ -153,20 +211,33 @@ start() {
  stop() {
  	logger -s -t policyrouting "Stopping policy routing"
  	olsrd_rmtables
@@ -318,3 +349,4 @@ Index: openwrt/feeds/luci/contrib/package/freifunk-policyrouting/Makefile
 +PKG_RELEASE:=7
  
  PKG_BUILD_DIR := $(BUILD_DIR)/$(PKG_NAME)
+ 
