update all

diff --git a/patches/luci-freifunk-policyrouting.patch b/patches/luci-freifunk-policyrouting.patch
--- a/patches/luci-freifunk-policyrouting.patch
+++ b/patches/luci-freifunk-policyrouting.patch
@@ -1,3 +1,16 @@
+diff --git a/contrib/package/freifunk-policyrouting/Makefile b/contrib/package/freifunk-policyrouting/Makefile
+index a9301ce..3a92224 100644
+--- a/contrib/package/freifunk-policyrouting/Makefile
++++ b/contrib/package/freifunk-policyrouting/Makefile
+@@ -4,7 +4,7 @@
+ include $(TOPDIR)/rules.mk
+ 
+ PKG_NAME:=freifunk-policyrouting
+-PKG_RELEASE:=6
++PKG_RELEASE:=7
+ 
+ PKG_BUILD_DIR := $(BUILD_DIR)/$(PKG_NAME)
+ 
 diff --git a/contrib/package/freifunk-policyrouting/files/etc/config/freifunk-policyrouting b/contrib/package/freifunk-policyrouting/files/etc/config/freifunk-policyrouting
 index 3dd2998..ff2c67c 100644
 --- a/contrib/package/freifunk-policyrouting/files/etc/config/freifunk-policyrouting
@@ -13,7 +26,7 @@ index 3dd2998..ff2c67c 100644
 +	option 'zones' 'freifunk'
  
 diff --git a/contrib/package/freifunk-policyrouting/files/etc/hotplug.d/iface/30-policyrouting b/contrib/package/freifunk-policyrouting/files/etc/hotplug.d/iface/30-policyrouting
-index 327e879..f6937f4 100644
+index 327e879..57a03ec 100644
 --- a/contrib/package/freifunk-policyrouting/files/etc/hotplug.d/iface/30-policyrouting
 +++ b/contrib/package/freifunk-policyrouting/files/etc/hotplug.d/iface/30-policyrouting
 @@ -4,7 +4,7 @@
@@ -61,26 +74,67 @@ index 327e879..f6937f4 100644
  			$cmd 2>&1 > /dev/null
  			if [ "$?" = 0 ]; then
  				logger -s -t policyrouting "Add route: $cmd (IPv6)"
-@@ -52,7 +61,7 @@ if [ "$ACTION" = "ifup" ] && [ "$enable" = "1" ]; then
+@@ -52,53 +61,20 @@ if [ "$ACTION" = "ifup" ] && [ "$enable" = "1" ]; then
  		for n in $networks; do
  			if [ "$INTERFACE" = "$n" ]; then
  				for p in $proto; do
 -					if [ ! "$(ip -$p ru s | grep "from all iif $dev lookup olsr-default")" ]; then
 +					if [ ! "$(ip -$p rule show | grep "from all iif $dev lookup olsr-default")" ]; then
++						logger -s -t policyrouting "Use mesh gateway for interface $dev (IPv$p)"
  						ip -$p rule add dev "$dev" lookup olsr-default prio 20000
  						if [ "$strict" != 0 ]; then
  							ip -$p rule add dev "$dev" unreachable prio 20001
-@@ -88,7 +97,7 @@ if [ "$ACTION" = "ifdown" ]; then
- 		for n in $networks; do
- 			if [ "$INTERFACE" = "$n" ]; then
- 				for p in $proto; do
+ 						fi
+-						if [ "$?" = 0 ]; then
+-							logger -s -t policyrouting "Use mesh gateway for interface $dev (IPv$p)"
+-							if [ -z "$(uci -P /var/state get freifunk-policyrouting.${INTERFACE})" ]; then
+-								uci -P /var/state set freifunk-policyrouting.${INTERFACE}="state"
+-							fi
+-							uci -P /var/state set freifunk-policyrouting.${INTERFACE}.device="$dev"
+-						else
+-							logger -s -t policyrouting "Error: Could not add rule: dev "$dev" lookup olsr-default prio 20000 (IPv$p)"
++						if [ -z "$(uci -P /var/state get freifunk-policyrouting.${INTERFACE})" ]; then
++							uci -P /var/state set freifunk-policyrouting.${INTERFACE}="state"
+ 						fi
++						uci -P /var/state set freifunk-policyrouting.${INTERFACE}.device="$dev"
+ 					fi
+ 				done
+ 			fi
+ 		done
+ 	fi
+-
+ fi
+ 
+-if [ "$ACTION" = "ifdown" ]; then
+-	dev="$(uci -q -P /var/state get freifunk-policyrouting.${INTERFACE}.device)"
+-	if [ -n "$dev" ]; then
+-		networks=""
+-		for z in $zones; do
+-			network_zone="$(uci -q get firewall.zone_${z}.network)"
+-			if [ -z "$network_zone" ]; then
+-				network_zone="$z"
+-			fi
+-			networks="$networks $network_zone"
+-		done
+-		for n in $networks; do
+-			if [ "$INTERFACE" = "$n" ]; then
+-				for p in $proto; do
 -					if [ "$(ip -$p ru s | grep "from all iif $dev lookup olsr-default")" ]; then
-+					if [ "$(ip -$p rule show | grep "from all iif $dev lookup olsr-default")" ]; then
- 						ip -$p rule del dev "$dev" lookup olsr-default prio 20000
- 						ip -$p rule del dev "$dev" unreachable prio 20001
- 						if [ "$?" = 0 ]; then
+-						ip -$p rule del dev "$dev" lookup olsr-default prio 20000
+-						ip -$p rule del dev "$dev" unreachable prio 20001
+-						if [ "$?" = 0 ]; then
+-							logger -s -t policyrouting "Remove rule: dev "$dev" lookup olsr-default prio 20000 (IPv$p)"
+-						else
+-							logger -s -t policyrouting "Error! Could not remove rule: dev "$dev" lookup olsr-default prio 20000 (IPv$p)"
+-						fi
+-					fi
+-				done
+-			fi
+-		done
+-	fi
+-fi
 diff --git a/contrib/package/freifunk-policyrouting/files/etc/init.d/freifunk-policyrouting b/contrib/package/freifunk-policyrouting/files/etc/init.d/freifunk-policyrouting
-index b3720e6..be81472 100755
+index 10cb445..381a05e 100755
 --- a/contrib/package/freifunk-policyrouting/files/etc/init.d/freifunk-policyrouting
 +++ b/contrib/package/freifunk-policyrouting/files/etc/init.d/freifunk-policyrouting
 @@ -5,7 +5,7 @@ START=15
@@ -92,28 +146,72 @@ index b3720e6..be81472 100755
  
  config_load freifunk-policyrouting
  config_get enable pr enable
-@@ -88,12 +88,14 @@ add_lookup_rule() {
+@@ -81,6 +81,8 @@ add_lookup_rule() {
+ 	name=${1/-/_}
+ 	lookup=$2
+ 	prio=$3
++	in=$4
++	name=$name"_"${in:-allif}"_"
+ 
+ 	if [ -z "$name" -o -z "$lookup" -o -z "$prio" ]; then
+ 		logger -s -t policyrouting "Missing parameters for add_rule!"
+@@ -91,21 +93,57 @@ add_lookup_rule() {
  			else
  				rule="rule"
  			fi
--
--			uci batch <<- EOF
--				set network.${name}ipv${p}="$rule"
--				set network.${name}ipv${p}.lookup="$lookup"
--				set network.${name}ipv${p}.priority="$prio"
--			EOF
 +			if [ "$(uci -q get network.${name}ipv${p})" != "$rule" ] ; then
 +				uci batch <<- EOF
 +					set network.${name}ipv${p}="$rule"
 +					set network.${name}ipv${p}.lookup="$lookup"
 +					set network.${name}ipv${p}.priority="$prio"
++					set network.${name}ipv${p}.in="$in"
++				EOF
++				uci commit network
++			fi
++		done
++	fi
++}
++
++add_action_rule() {
++	name=${1/-/_}
++	action=$2
++	prio=$3
++	in=$4
++	name=$name"_"${in:-allif}"_"
+ 
+-			uci batch <<- EOF
+-				set network.${name}ipv${p}="$rule"
+-				set network.${name}ipv${p}.lookup="$lookup"
+-				set network.${name}ipv${p}.priority="$prio"
+-			EOF
++	if [ -z "$name" -o -z "$action" -o -z "$prio" ]; then
++		logger -s -t policyrouting "Missing parameters for add_action!"
++	else
++		for p in $proto; do
++			if [ "$p" = "6" ]; then
++				rule="rule6"
++			else
++				rule="rule"
++			fi
++			if [ "$(uci -q get network.${name}ipv${p})" != "$rule" ] ; then
++				uci batch <<- EOF
++					set network.${name}ipv${p}="$rule"
++					set network.${name}ipv${p}.action="$action"
++					set network.${name}ipv${p}.priority="$prio"
++					set network.${name}ipv${p}.in="$in"
 +				EOF
 +				uci commit network
 +			fi
  		done
  	fi
  }
-@@ -103,6 +105,7 @@ del_lookup_rule() {
+ 
+-del_lookup_rule() {
++
++del_rule() {
+ 	name=${1/-/_}
++	in=$2
++	name=$name"_"${in:-allif}"_"
  	for p in $proto; do
  		uci -q delete network.${name}ipv${p}
  	done
@@ -121,7 +219,7 @@ index b3720e6..be81472 100755
  }
  
  start() {
-@@ -110,7 +113,7 @@ start() {
+@@ -113,7 +151,7 @@ start() {
  		logger -s -t policyrouting "Starting policy routing."
  		rt_tables
  		olsrd_intalltables
@@ -130,11 +228,52 @@ index b3720e6..be81472 100755
  
  		add_lookup_rule olsr olsr 1000
  		add_lookup_rule localnets localnets 2000
-@@ -131,17 +134,11 @@ stop() {
- 	del_lookup_rule olsr-default
- 	del_lookup_rule olsr
- 	del_lookup_rule localnets
+@@ -121,6 +159,20 @@ start() {
+ 		if [ "$fallback" = 1 ]; then
+ 			add_lookup_rule olsr-default olsr-default 100000
+ 		fi
++		networks=""
++		for z in $zones; do
++			network_zone="$(uci -q get firewall.zone_${z}.network)"
++			if [ -z "$network_zone" ]; then
++				network_zone="$z"
++			fi
++			networks="$networks $network_zone"
++		done
++		for n in $networks; do
++			add_lookup_rule olsr-default olsr-default 20000 $n
++			if [ "$strict" != 0 ]; then
++				add_action_rule olsr-default_unreachable unreachable 20001 $n
++			fi
++		done
+ 	fi
+ 	uci commit network
+ 	if [ ! "$1" = "noservicerestart" ]; then
+@@ -131,20 +183,28 @@ start() {
+ stop() {
+ 	logger -s -t policyrouting "Stopping policy routing"
+ 	olsrd_rmtables
+-	del_lookup_rule olsr-default
+-	del_lookup_rule olsr
+-	del_lookup_rule localnets
 -	uci commit network
++	del_rule olsr-default
++	del_rule olsr
++	del_rule localnets
++	networks=""
++	for z in $zones; do
++		network_zone="$(uci -q get firewall.zone_${z}.network)"
++		if [ -z "$network_zone" ]; then
++			network_zone="$z"
++		fi
++		networks="$networks $network_zone"
++	done
++	for n in $networks; do
++		del_rule olsr-default $n
++		if [ "$strict" != 0 ]; then
++			del_rule olsr-default_unreachable $n
++		fi
++	done
  	restart_services
  	echo "Hint: To completely disable freifunk-policyrouting set enable=0 in /etc/config/freifunk-policyrouting."
  }
