rebase luci-freifunk-gwcheck.patch

diff --git a/patches/luci-freifunk-policyrouting.patch b/patches/luci-freifunk-policyrouting.patch
--- a/patches/luci-freifunk-policyrouting.patch
+++ b/patches/luci-freifunk-policyrouting.patch
@@ -1,18 +1,5 @@
-diff --git a/contrib/package/freifunk-policyrouting/Makefile b/contrib/package/freifunk-policyrouting/Makefile
-index 22fdc59..20146de 100644
---- a/contrib/package/freifunk-policyrouting/Makefile
-+++ b/contrib/package/freifunk-policyrouting/Makefile
-@@ -15,7 +15,7 @@ define Package/freifunk-policyrouting
-   CATEGORY:=LuCI
-   SUBMENU:=9. Freifunk
-   TITLE:=Freifunk policy routing addon
--  DEPENDS:=+ip
-+
- endef
- 
- define Package/freifunk-policyrouting/description
 diff --git a/contrib/package/freifunk-policyrouting/files/etc/config/freifunk-policyrouting b/contrib/package/freifunk-policyrouting/files/etc/config/freifunk-policyrouting
-index 3dd2998..ea2bc92 100644
+index 3dd2998..ff2c67c 100644
 --- a/contrib/package/freifunk-policyrouting/files/etc/config/freifunk-policyrouting
 +++ b/contrib/package/freifunk-policyrouting/files/etc/config/freifunk-policyrouting
 @@ -1,7 +1,6 @@
@@ -26,7 +13,7 @@ index 3dd2998..ea2bc92 100644
 +	option 'zones' 'freifunk'
  
 diff --git a/contrib/package/freifunk-policyrouting/files/etc/hotplug.d/iface/30-policyrouting b/contrib/package/freifunk-policyrouting/files/etc/hotplug.d/iface/30-policyrouting
-index 327e879..4ef9703 100644
+index 327e879..f6937f4 100644
 --- a/contrib/package/freifunk-policyrouting/files/etc/hotplug.d/iface/30-policyrouting
 +++ b/contrib/package/freifunk-policyrouting/files/etc/hotplug.d/iface/30-policyrouting
 @@ -4,7 +4,7 @@
@@ -38,7 +25,7 @@ index 327e879..4ef9703 100644
  
  config_load freifunk-policyrouting
  config_get enable pr enable
-@@ -14,14 +14,14 @@ config_get zones pr zones
+@@ -14,14 +14,23 @@ config_get zones pr zones
  
  if [ "$ACTION" = "ifup" ] && [ "$enable" = "1" ]; then
  	network_get_subnet net $INTERFACE
@@ -53,10 +40,19 @@ index 327e879..4ef9703 100644
 -				cmd="ip r a $NETWORK/$PREFIX dev $dev table localnets"
 +			if [ ! "$(ip route show table localnets |grep "$NETWORK/$PREFIX dev")" ]; then
 +				cmd="ip route add $NETWORK/$PREFIX dev $dev table localnets"
++				$cmd
++				if [ "$?" = 0 ]; then
++					logger -s -t policyrouting "Add route: $cmd"
++				else
++					logger -s -t policyrouting "Error! Could not add route: $cmd"
++				fi
++			fi
++			if [ ! "$(ip route show table olsr |grep "$NETWORK/$PREFIX dev")" ]; then
++				cmd="ip route add $NETWORK/$PREFIX dev $dev table olsr"
  				$cmd
  				if [ "$?" = 0 ]; then
  					logger -s -t policyrouting "Add route: $cmd"
-@@ -33,7 +33,7 @@ if [ "$ACTION" = "ifup" ] && [ "$enable" = "1" ]; then
+@@ -33,7 +42,7 @@ if [ "$ACTION" = "ifup" ] && [ "$enable" = "1" ]; then
  		fi
  
  		if [ -n "$net6" ]; then
@@ -65,7 +61,7 @@ index 327e879..4ef9703 100644
  			$cmd 2>&1 > /dev/null
  			if [ "$?" = 0 ]; then
  				logger -s -t policyrouting "Add route: $cmd (IPv6)"
-@@ -52,7 +52,7 @@ if [ "$ACTION" = "ifup" ] && [ "$enable" = "1" ]; then
+@@ -52,7 +61,7 @@ if [ "$ACTION" = "ifup" ] && [ "$enable" = "1" ]; then
  		for n in $networks; do
  			if [ "$INTERFACE" = "$n" ]; then
  				for p in $proto; do
@@ -74,7 +70,7 @@ index 327e879..4ef9703 100644
  						ip -$p rule add dev "$dev" lookup olsr-default prio 20000
  						if [ "$strict" != 0 ]; then
  							ip -$p rule add dev "$dev" unreachable prio 20001
-@@ -88,7 +88,7 @@ if [ "$ACTION" = "ifdown" ]; then
+@@ -88,7 +97,7 @@ if [ "$ACTION" = "ifdown" ]; then
  		for n in $networks; do
  			if [ "$INTERFACE" = "$n" ]; then
  				for p in $proto; do
